import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("Side item menu uses focused metadata, move, and Find link actions", async () => {
  const source = await readFile(new URL("../src/side-palette/side-palette-view.ts", import.meta.url), "utf8");
  const main = await readFile(new URL("../src/main.ts", import.meta.url), "utf8");
  const modal = await readFile(new URL("../src/ui/modal.ts", import.meta.url), "utf8");
  const canvas = await readFile(new URL("../src/canvas/canvas-adapter.ts", import.meta.url), "utf8");

  assert.match(source, /setTitle\("Edit tags, label & caption"\)/);
  assert.match(source, /setTitle\("Rename linked item"\)/);
  assert.match(source, /item\.type === "image" \|\| item\.type === "markdown" \|\| item\.type === "group"/);
  assert.match(source, /setTitle\("Convert to shared Markdown…"\)/);
  assert.match(source, /new CardToMarkdownModal/);
  assert.match(source, /this\.plugin\.renameLinkedItem\(item\.id, value\)/);
  assert.doesNotMatch(canvas, /else if \(item\.type === "group"[\s\S]{0,600}item\.displayTitle/);
  assert.match(source, /setTitle\("Move to…"\)/);
  assert.doesNotMatch(source, /setTitle\(`Move to \$\{collection\.name\}`\)/);
  assert.match(source, /setTitle\("Locate on Canvas"\)/);
  assert.match(source, /allInMini \? "Remove from Mini Palette" : "Export to Mini Palette"/);
  assert.match(source, /allInMini \? this\.plugin\.store\.removeMiniStorageItems\(targetIds\) : this\.plugin\.sendItemsToMini\(targetIds\)/);
  assert.match(source, /setTitle\("Export Workspace to Canvas"\)[\s\S]{0,120}exportActiveWorkspace\(\)/);
  assert.doesNotMatch(source, /header\.createEl\("button", \{ text: "Export to Mini Palette" \}\)/);
  assert.doesNotMatch(source, /header\.createEl\("button", \{ text: "Export Workspace to Canvas" \}\)/);
  assert.doesNotMatch(source, /Export selected items to Mini Palette/);
  assert.match(main, /collectCanvasItems\(items\)[\s\S]{0,160}miniPalette\.tab = "collect"/);
  assert.match(main, /sendItemsToMini\(itemIds: string\[\]\)/);
  assert.doesNotMatch(source, /setTitle\("Open original"\)/);
  assert.match(source, /setTitle\("Open source file"\)/);
  assert.match(source, /application\/x-canvas-palette-collection/);
  assert.match(source, /setTitle\("Export collection to Canvas"\)[\s\S]{0,160}exportCollectionSubtree\(collection\.id\)/);
  assert.match(source, /this\.mountOutlineDropTarget\(rootRow, workspaceId, null\)/);
  assert.match(source, /selected\.includes\(itemId\) \? selected : \[itemId\]/);
  assert.match(source, /this\.plugin\.store\.moveCollection\(draggedCollectionId, collectionId\)/);
  assert.match(main, /new FindLinkModal\(this\.app, item\.displayTitle, locations/);
  assert.match(modal, /"Tags, label & caption"/);
  assert.match(modal, /cls: "cp-tag-label-caption"/);
  assert.match(modal, /let captionTouched = false/);
  assert.match(modal, /caption: captionTouched \|\| sharedCaptions\.size === 1 \? caption\.value\.trim\(\) : item\.caption/);
  assert.match(modal, /this\.virtualList<string>\(tagListHost/);
  assert.match(modal, /this\.virtualList<string>\(labelListHost/);
  assert.match(modal, /placeholder: "Search tags"/);
  assert.match(modal, /placeholder: "Search labels"/);
  assert.match(modal, /const rowHeight = 36/);
  assert.match(modal, /const overscan = 4/);
});
